In [1]:
import numpy as np
import pickle
import optuna

In [11]:
# Load bounds
with open(r"D:\UST Project\UST_Analog_automation\notebooks\new_data_exp\trained_models\param_bounds.pkl", "rb") as f:
    bounds = pickle.load(f)

feature_names = list(bounds.keys())  # ['a','b','c','d']

# Log sampling config (optimizer-side only)
feature_config = {
    "a": {"log": True},
    "b": {"log": False},  # includes 0
    "c": {"log": True},
    "d": {"log": True},
}

# Load trained forward models
model_gain = pickle.load(open(r"D:\UST Project\UST_Analog_automation\notebooks\new_data_exp\trained_models\model_gain_xgboost.pkl", "rb"))
model_pm   = pickle.load(open(r"D:\UST Project\UST_Analog_automation\notebooks\new_data_exp\trained_models\model_pm_xgboost.pkl", "rb"))
model_ugf  = pickle.load(open(r"D:\UST Project\UST_Analog_automation\notebooks\new_data_exp\trained_models\model_ugf_xgboost.pkl", "rb"))

In [25]:
GAIN_TARGET = 55.10516431	   # example
PM_MAX      = 66.97095421    # constraint
UGF_TARGET  = 120.42698870000001	  # example

In [26]:
# ============================================================
# 4. INVERSE LOSS FUNCTION
# ============================================================
def inverse_loss(x):
    """
    x shape: (1, 4)
    """
    gain = model_gain.predict(x)[0]
    pm   = model_pm.predict(x)[0]
    ugf  = model_ugf.predict(x)[0]

    loss = (
        abs(gain - GAIN_TARGET) +
        max(0.0, PM_MAX - pm) +
        abs(ugf - UGF_TARGET)
    )
    return loss

In [27]:
def objective(trial):
    x = []

    for f in feature_names:
        low, high = bounds[f]

        if feature_config[f]["log"]:
            val = trial.suggest_float(f, low, high, log=True)
        else:
            val = trial.suggest_float(f, low, high)

        x.append(val)

    x = np.array(x).reshape(1, -1)
    return inverse_loss(x)

In [28]:
study = optuna.create_study(
    direction="minimize",
    sampler=optuna.samplers.TPESampler(
        seed=42,
        n_startup_trials=50
    )
)

study.optimize(objective, n_trials=200, show_progress_bar=True)

[I 2026-02-06 21:01:18,283] A new study created in memory with name: no-name-1821c08a-8adc-4fae-b6e5-ee596d47c6dd

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-02-06 21:01:18,327] Trial 0 finished with value: 156.96646118164062 and parameters: {'a': 6.59269988761102e-06, 'b': 0.0003698270095505816, 'c': 4.462395092148129e-06, 'd': 6.37710619087497e-05}. Best is trial 0 with value: 156.96646118164062.
[I 2026-02-06 21:01:18,331] Trial 1 finished with value: 117.59207153320312 and parameters: {'a': 5.478384061253937e-06, 'b': 6.068172801571452e-05, 'c': 2.521068595986405e-06, 'd': 7.999520174016835e-05}. Best is trial 1 with value: 117.59207153320312.
[I 2026-02-06 21:01:18,336] Trial 2 finished with value: 111.35490417480469 and parameters: {'a': 7.987991737671789e-06, 'b': 0.0002754395954973417, 'c': 2.44222604110033e-06, 'd': 8.734449411161188e-05}. Best is trial 2 with value: 111.35490417480469.
[I 2026-02-06 21:01:18,340] Trial 3 finished with value: 141.96209716796875 and parameters: {'a': 9.717639958417919e-06, 'b': 8.259972294864981e-05, 'c': 2.7997458439219924e-06, 'd': 4.485592596776692e-05}. Best is trial 2 with value: 111.35490417480469.
[I 2026-02-06 21:01:18,343] Trial 4 finished with value: 141.27517700195312 and parameters: {'a': 6.211483270845925e-06, 'b': 0.00020412977962415204, 'c': 3.4606444448191815e-06, 'd': 4.9146974437445996e-05}. Best is trial 2 with value: 111.35490417480469.
[I 2026-02-06 21:01:18,347] Trial 5 finished with value: 137.6956787109375 and parameters: {'a': 8.06099958229809e-06, 'b': 5.4262986249169684e-05, 'c': 3.074069558843862e-06, 'd': 5.237739292708591e-05}. Best is trial 2 with value: 111.35490417480469.
[I 2026-02-06 21:01:18,351] Trial 6 finished with value: 134.38876342773438 and parameters: {'a': 7.064223059395701e-06, 'b': 0.000305432742323517, 'c': 2.8424089252279494e-06, 'd': 5.9368702822201856e-05}. Best is trial 2 with value: 111.35490417480469.
[I 2026-02-06 21:01:18,356] Trial 7 finished with value: 77.46894836425781 and parameters: {'a': 7.929321846882619e-06, 'b': 1.8069168742707666e-05, 'c': 4.015814497492794e-06, 'd': 4.436905135059032e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,361] Trial 8 finished with value: 119.6046142578125 and parameters: {'a': 5.071993793550197e-06, 'b': 0.0003691156199945631, 'c': 5.439279965906966e-06, 'd': 7.617328441539014e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,367] Trial 9 finished with value: 169.41012573242188 and parameters: {'a': 6.2134389123683105e-06, 'b': 3.799436444358072e-05, 'c': 4.2854172279401104e-06, 'd': 5.575670798948261e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,371] Trial 10 finished with value: 115.89613342285156 and parameters: {'a': 5.322902052338975e-06, 'b': 0.000192623372374065, 'c': 2.4709583163365733e-06, 'd': 8.297361707345819e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,373] Trial 11 finished with value: 134.9903106689453 and parameters: {'a': 5.976766141255695e-06, 'b': 0.00025772057234364304, 'c': 3.1254581023085998e-06, 'd': 5.966287580700375e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,378] Trial 12 finished with value: 126.12287139892578 and parameters: {'a': 7.62812723697779e-06, 'b': 7.190821683042004e-05, 'c': 5.457526788101741e-06, 'd': 7.405631685508992e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,382] Trial 13 finished with value: 152.68112182617188 and parameters: {'a': 1.064032853660455e-05, 'b': 0.00034808703397174, 'c': 3.9831306681489e-06, 'd': 8.386090441252278e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,386] Trial 14 finished with value: 139.51641845703125 and parameters: {'a': 5.173737901106338e-06, 'b': 7.62371570964713e-05, 'c': 2.4937552888076592e-06, 'd': 5.0587734856376605e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,391] Trial 15 finished with value: 159.23060607910156 and parameters: {'a': 6.672144709192133e-06, 'b': 0.00010555452914591692, 'c': 4.84359036019393e-06, 'd': 5.195270523379218e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,396] Trial 16 finished with value: 122.64857482910156 and parameters: {'a': 6.0900185450470645e-06, 'b': 0.0002111082879220838, 'c': 2.7043823008886147e-06, 'd': 7.57741529957081e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,401] Trial 17 finished with value: 163.65008544921875 and parameters: {'a': 5.112980584423259e-06, 'b': 0.00038389813013935825, 'c': 4.617207467475388e-06, 'd': 4.544163845825892e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,403] Trial 18 finished with value: 154.7191925048828 and parameters: {'a': 4.8225112371119566e-06, 'b': 0.00031721376175364486, 'c': 4.368359125306281e-06, 'd': 7.12178631067335e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,407] Trial 19 finished with value: 154.28463745117188 and parameters: {'a': 9.226793906595098e-06, 'b': 2.880330288437459e-05, 'c': 3.251758679614844e-06, 'd': 4.236120918689747e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,410] Trial 20 finished with value: 145.90545654296875 and parameters: {'a': 9.973400548968826e-06, 'b': 0.00024246241036760587, 'c': 3.176684128279207e-06, 'd': 4.052464525295785e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,414] Trial 21 finished with value: 156.36599731445312 and parameters: {'a': 6.247057630154797e-06, 'b': 0.00012649601960341476, 'c': 4.453376137841825e-06, 'd': 6.590791502827409e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,418] Trial 22 finished with value: 128.92430114746094 and parameters: {'a': 1.0179230067714932e-05, 'b': 0.00018369118089456562, 'c': 2.6559454315475213e-06, 'd': 7.027304110798463e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,422] Trial 23 finished with value: 158.88185119628906 and parameters: {'a': 9.145184547767176e-06, 'b': 0.0002183363247050562, 'c': 4.612212050574276e-06, 'd': 5.834941960298048e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,426] Trial 24 finished with value: 144.64739990234375 and parameters: {'a': 7.474717499124772e-06, 'b': 0.00016631307135455927, 'c': 2.4522508303192285e-06, 'd': 4.2075837080453e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,430] Trial 25 finished with value: 135.91717529296875 and parameters: {'a': 4.929540602817032e-06, 'b': 0.0002475630772122404, 'c': 3.1324701779015245e-06, 'd': 5.908448200302371e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,435] Trial 26 finished with value: 126.3545913696289 and parameters: {'a': 1.0356300199328617e-05, 'b': 9.697445277590612e-05, 'c': 3.397994178319288e-06, 'd': 7.283774693594149e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,439] Trial 27 finished with value: 150.97927856445312 and parameters: {'a': 5.82684748513348e-06, 'b': 2.9945115641481626e-05, 'c': 3.067842431403213e-06, 'd': 4.4020697072544166e-05}. Best is trial 7 with value: 77.46894836425781.
[I 2026-02-06 21:01:18,443] Trial 28 finished with value: 12.800487518310547 and parameters: {'a': 1.0552330642980089e-05, 'b': 0.00031435810034221657, 'c': 4.104772762118505e-06, 'd': 8.035418320123899e-05}. Best is trial 28 with value: 12.800487518310547.
[I 2026-02-06 21:01:18,448] Trial 29 finished with value: 9.691333770751953 and parameters: {'a': 9.483614776471383e-06, 'b': 7.257558499361494e-05, 'c': 5.112722632110138e-06, 'd': 6.064523017394982e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,451] Trial 30 finished with value: 145.90545654296875 and parameters: {'a': 9.513941353648752e-06, 'b': 0.00034857870918806894, 'c': 3.142166095096753e-06, 'd': 4.215293101604646e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,465] Trial 31 finished with value: 153.2349853515625 and parameters: {'a': 5.822588331874454e-06, 'b': 0.00016614454537860395, 'c': 4.799783910646512e-06, 'd': 7.962695300736946e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,478] Trial 32 finished with value: 144.15338134765625 and parameters: {'a': 4.828357961202828e-06, 'b': 0.00019868024103010073, 'c': 3.418289183682043e-06, 'd': 4.635128113953638e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,486] Trial 33 finished with value: 139.9140625 and parameters: {'a': 5.313111253904574e-06, 'b': 0.00013133199782235701, 'c': 5.335561416988935e-06, 'd': 5.04966305546759e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,494] Trial 34 finished with value: 109.32437896728516 and parameters: {'a': 7.449791919298789e-06, 'b': 0.00027347374229316117, 'c': 3.2660173976202607e-06, 'd': 8.748316186753038e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,503] Trial 35 finished with value: 159.85304260253906 and parameters: {'a': 1.084924455889034e-05, 'b': 9.794308647200041e-05, 'c': 3.6575236954286463e-06, 'd': 4.9550433413879986e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,509] Trial 36 finished with value: 41.38835906982422 and parameters: {'a': 6.1102070479945024e-06, 'b': 1.4348989322660638e-05, 'c': 4.022691851352983e-06, 'd': 5.8790267378872045e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,512] Trial 37 finished with value: 43.233863830566406 and parameters: {'a': 5.01399876639201e-06, 'b': 0.00010839322380622403, 'c': 5.181219634309469e-06, 'd': 4.704185498350994e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,516] Trial 38 finished with value: 138.6095733642578 and parameters: {'a': 5.426992065387442e-06, 'b': 0.00019039668324048774, 'c': 5.5323255368483686e-06, 'd': 4.714134236515814e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,526] Trial 39 finished with value: 125.71183013916016 and parameters: {'a': 8.483430678382443e-06, 'b': 0.00029626934490521733, 'c': 2.935325998710263e-06, 'd': 7.117015887726076e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,530] Trial 40 finished with value: 22.184814453125 and parameters: {'a': 6.555063335618652e-06, 'b': 0.0002459663990256549, 'c': 4.105210849991878e-06, 'd': 6.046218952046348e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,535] Trial 41 finished with value: 143.3843231201172 and parameters: {'a': 5.181622581509813e-06, 'b': 0.00032493191901196753, 'c': 3.149567053504136e-06, 'd': 4.497443397256532e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,540] Trial 42 finished with value: 87.06330871582031 and parameters: {'a': 4.968731658835679e-06, 'b': 0.00022985682309657719, 'c': 4.261271421133921e-06, 'd': 3.894351611397697e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,544] Trial 43 finished with value: 69.22506713867188 and parameters: {'a': 7.4076353367382115e-06, 'b': 8.810665270580019e-05, 'c': 4.145909818160137e-06, 'd': 4.4513733601312224e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,548] Trial 44 finished with value: 60.13529968261719 and parameters: {'a': 8.619662967978646e-06, 'b': 0.00015043970164909737, 'c': 5.30769711346668e-06, 'd': 4.3145523152119574e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,551] Trial 45 finished with value: 25.393985748291016 and parameters: {'a': 6.408342822064695e-06, 'b': 4.414109763642003e-05, 'c': 5.2538422267017525e-06, 'd': 8.075543097898879e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,553] Trial 46 finished with value: 157.87677001953125 and parameters: {'a': 5.972522139882698e-06, 'b': 0.0002567331999216542, 'c': 4.796561749432632e-06, 'd': 6.146561540466501e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,558] Trial 47 finished with value: 112.27224731445312 and parameters: {'a': 7.518658414415043e-06, 'b': 9.408032349321389e-05, 'c': 2.596993716907229e-06, 'd': 8.212696895474595e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,562] Trial 48 finished with value: 141.30905151367188 and parameters: {'a': 1.0293763343369835e-05, 'b': 0.0002462758970879897, 'c': 3.1986471472072175e-06, 'd': 5.1621692683647074e-05}. Best is trial 29 with value: 9.691333770751953.
[I 2026-02-06 21:01:18,565] Trial 49 finished with value: 4.057231903076172 and parameters: {'a': 8.879245714686918e-06, 'b': 0.00034897508372231853, 'c': 5.089070325405271e-06, 'd': 7.435451080716379e-05}. Best is trial 49 with value: 4.057231903076172.
[I 2026-02-06 21:01:18,580] Trial 50 finished with value: 170.61154174804688 and parameters: {'a': 6.5999387095985235e-06, 'b': 8.245209695107944e-07, 'c': 5.0403312656399606e-06, 'd': 6.603316393646877e-05}. Best is trial 49 with value: 4.057231903076172.
[I 2026-02-06 21:01:18,590] Trial 51 finished with value: 158.22413635253906 and parameters: {'a': 6.8767031316502835e-06, 'b': 5.261758395946751e-05, 'c': 3.85839603508632e-06, 'd': 5.369082740886953e-05}. Best is trial 49 with value: 4.057231903076172.
[I 2026-02-06 21:01:18,599] Trial 52 finished with value: 168.23785400390625 and parameters: {'a': 6.413355706889254e-06, 'b': 1.6828050041923292e-06, 'c': 3.6049531021364538e-06, 'd': 5.641126218642546e-05}. Best is trial 49 with value: 4.057231903076172.
[I 2026-02-06 21:01:18,608] Trial 53 finished with value: 155.60537719726562 and parameters: {'a': 7.066925612433891e-06, 'b': 5.2343429857736344e-05, 'c': 3.860235453268188e-06, 'd': 6.301684485369504e-05}. Best is trial 49 with value: 4.057231903076172.
[I 2026-02-06 21:01:18,619] Trial 54 finished with value: 0.478302001953125 and parameters: {'a': 1.1037862873529018e-05, 'b': 0.0002894018174768268, 'c': 5.071226838664409e-06, 'd': 7.787757818455481e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,627] Trial 55 finished with value: 154.30111694335938 and parameters: {'a': 1.1079887297593865e-05, 'b': 0.0002916230196167523, 'c': 4.97513205811045e-06, 'd': 7.892535032651208e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,636] Trial 56 finished with value: 151.43484497070312 and parameters: {'a': 9.775049457894345e-06, 'b': 0.0003265122680013121, 'c': 4.613286759613483e-06, 'd': 8.94126126493614e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,644] Trial 57 finished with value: 127.5901107788086 and parameters: {'a': 1.1149988529669713e-05, 'b': 0.0003499452811021821, 'c': 5.596975672451711e-06, 'd': 6.841275186207335e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,653] Trial 58 finished with value: 156.691162109375 and parameters: {'a': 1.0621240313329807e-05, 'b': 0.00027121303636198853, 'c': 5.024954190642447e-06, 'd': 7.617102388018274e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,662] Trial 59 finished with value: 13.744258880615234 and parameters: {'a': 8.957774084264542e-06, 'b': 0.00036856655151596145, 'c': 5.204700989659309e-06, 'd': 8.426066788359837e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,671] Trial 60 finished with value: 13.744258880615234 and parameters: {'a': 8.72717344140967e-06, 'b': 0.0003689753947984625, 'c': 5.152387528217262e-06, 'd': 8.487172920067271e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,680] Trial 61 finished with value: 18.4427490234375 and parameters: {'a': 8.722440972009475e-06, 'b': 0.00037111176071166253, 'c': 5.130092673650456e-06, 'd': 8.621728267896851e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,687] Trial 62 finished with value: 18.4427490234375 and parameters: {'a': 8.583411269435258e-06, 'b': 0.00038233430807658303, 'c': 5.110592782202057e-06, 'd': 8.689226062811472e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,696] Trial 63 finished with value: 152.4130401611328 and parameters: {'a': 8.96220364382486e-06, 'b': 0.0003668357261763392, 'c': 4.912582142879466e-06, 'd': 8.422551042858057e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,706] Trial 64 finished with value: 153.2349853515625 and parameters: {'a': 8.045555476551646e-06, 'b': 0.00036555960205650713, 'c': 4.698990665182793e-06, 'd': 7.809770816757479e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,715] Trial 65 finished with value: 114.31575775146484 and parameters: {'a': 9.489749823359178e-06, 'b': 0.00033740323580869934, 'c': 5.362688686603681e-06, 'd': 8.457471717682934e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,723] Trial 66 finished with value: 4.057231903076172 and parameters: {'a': 8.351752594436747e-06, 'b': 0.00031235032822387465, 'c': 5.173522478479529e-06, 'd': 7.373923756807932e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,733] Trial 67 finished with value: 153.49960327148438 and parameters: {'a': 7.814336762643633e-06, 'b': 0.0003166428188754414, 'c': 4.476638322809558e-06, 'd': 7.424737071576638e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,743] Trial 68 finished with value: 152.94503784179688 and parameters: {'a': 8.251696869012504e-06, 'b': 0.0003095918430956142, 'c': 4.873095840919832e-06, 'd': 7.772595764119343e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,752] Trial 69 finished with value: 114.31575775146484 and parameters: {'a': 9.033729004324688e-06, 'b': 0.0003399522076750698, 'c': 5.445576185843333e-06, 'd': 8.14177106345267e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,761] Trial 70 finished with value: 4.057231903076172 and parameters: {'a': 9.476415367724008e-06, 'b': 0.0002909788802355776, 'c': 5.2030023109637085e-06, 'd': 7.365777967250919e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,770] Trial 71 finished with value: 4.057231903076172 and parameters: {'a': 9.3129400493509e-06, 'b': 0.0002906772531985423, 'c': 5.222479413146339e-06, 'd': 7.362621669839977e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,780] Trial 72 finished with value: 155.3839111328125 and parameters: {'a': 9.422246270986135e-06, 'b': 0.00028961008438237927, 'c': 4.777948018965682e-06, 'd': 6.88689704999178e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,787] Trial 73 finished with value: 4.057231903076172 and parameters: {'a': 9.951472554399215e-06, 'b': 0.0002830113403983674, 'c': 5.257824925262971e-06, 'd': 7.266946696901362e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,796] Trial 74 finished with value: 154.38238525390625 and parameters: {'a': 9.998590395928245e-06, 'b': 0.0002833674229047714, 'c': 4.967458255282103e-06, 'd': 7.354621393681777e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,805] Trial 75 finished with value: 119.50651550292969 and parameters: {'a': 9.800372386273357e-06, 'b': 0.00030328702737382517, 'c': 5.426534124758412e-06, 'd': 7.512675103746387e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,814] Trial 76 finished with value: 127.31755828857422 and parameters: {'a': 1.056994477429061e-05, 'b': 0.00026174699010916955, 'c': 5.482387787641786e-06, 'd': 7.237503692452896e-05}. Best is trial 54 with value: 0.478302001953125.
[I 2026-02-06 21:01:18,823] Trial 77 finished with value: 156.06475830078125 and parameters: {'a': 1.0010028603894947e-05, 'b': 0.0003031971109131894, 'c': 4.471131078598046e-06, 'd': 6.798107167367867e-05}. Best is trial 54 with value: 0.478302001953125.

In [29]:
best_params = study.best_params
x_best = np.array([best_params[f] for f in feature_names]).reshape(1, -1)

gain_best = model_gain.predict(x_best)[0]
pm_best   = model_pm.predict(x_best)[0]
ugf_best  = model_ugf.predict(x_best)[0]

print("\n===== INVERSE PREDICTION =====")
for k in feature_names:
    print(f"{k} = {best_params[k]:.6e}")

print("\nPredicted outputs:")
print(f"GAIN = {gain_best:.6f}")
print(f"PM   = {pm_best:.6f}")
print(f"UGF  = {ugf_best:.6f}")
print(f"Final loss = {study.best_value:.6f}")

===== INVERSE PREDICTION =====
a = 1.103786e-05
b = 2.894018e-04
c = 5.071227e-06
d = 7.787758e-05

Predicted outputs:
GAIN = 54.916481
PM   = 68.266685
UGF  = 120.716606
Final loss = 0.478302

In [24]:
import pandas as pd

df = pd.read_csv("Opam.csv")
pd.set_option('display.float_format', '{:.10f}'.format)


df.head()

,a,b,c,d,gain,pm,ugf
0,0.0000112000,0.0001320120,0.0000024000,0.0000384000,18.7427113100,87.2589267500,12.8594501900
1,0.0000112000,0.0001320120,0.0000024000,0.0000427000,20.0224857400,88.4842564900,14.2978920500
2,0.0000112000,0.0001320120,0.0000024000,0.0000469000,21.2202001200,89.6240725500,15.5129365100
3,0.0000112000,0.0001320120,0.0000024000,0.0000512000,22.3550526600,90.9081618400,17.4676334600
4,0.0000112000,0.0001320120,0.0000024000,0.0000555000,23.4437963200,92.1196945900,19.5720128900

In [14]:
print("\n===== STABILITY CHECK =====")
for i in range(5):
    noise = np.random.normal(0, 5e-8, size=x_best.shape)
    g = model_gain.predict(x_best + noise)[0]
    p = model_pm.predict(x_best + noise)[0]
    u = model_ugf.predict(x_best + noise)[0]
    print(f"{i+1}: GAIN={g:.4f}, PM={p:.4f}, UGF={u:.4f}")

===== STABILITY CHECK =====
1: GAIN=18.7872, PM=86.4662, UGF=12.0975
2: GAIN=18.7872, PM=86.4662, UGF=12.0975
3: GAIN=18.7872, PM=86.4662, UGF=12.0975
4: GAIN=18.7872, PM=86.4662, UGF=12.0975
5: GAIN=18.7872, PM=86.4662, UGF=12.0975

In [ ]:
print("\n===== TOP 5 INVERSE SOLUTIONS =====")
top_trials = sorted(study.trials, key=lambda t: t.value)[:5]

for i, t in enumerate(top_trials):
    print(f"\nSolution {i+1} | Loss = {t.value:.6f}")
    for f in feature_names:
        print(f"{f} = {t.params[f]:.6e}")

In [39]:
import pandas as pd 

df = pd.read_csv("Opam.csv")

df.head()

,a,b,c,d,gain,pm,ugf
0,0.0000048000000000,0.0000448000000000,0.0000024000000000,0.0000384000000000,18.9109775499999984,86.2353259100000002,12.1724450399999995
1,0.0000048000000000,0.0000448000000000,0.0000024000000000,0.0000427000000000,20.1793160600000014,87.4904806299999933,13.6422904700000007
2,0.0000048000000000,0.0000448000000000,0.0000024000000000,0.0000469000000000,21.3631409199999993,88.6525631399999980,14.8823551999999992
3,0.0000048000000000,0.0000448000000000,0.0000024000000000,0.0000512000000000,22.4827260200000012,89.7777121200000039,16.0733908000000021
4,0.0000048000000000,0.0000448000000000,0.0000024000000000,0.0000555000000000,23.5539255099999991,91.0271390599999961,18.2064033899999984

In [40]:
pd.set_option('display.float_format', '{:.16f}'.format)