In [1]:
import numpy as np
import pickle
import optuna

In [2]:
# Load bounds
with open(r"D:\UST Project\UST_Analog_automation\notebooks\new_data_exp\trained_models\param_bounds.pkl", "rb") as f:
    bounds = pickle.load(f)

feature_names = list(bounds.keys())  # ['a','b','c','d']

# Log sampling config (optimizer-side only)
feature_config = {
    "a": {"log": True},
    "b": {"log": False},  # includes 0
    "c": {"log": True},
    "d": {"log": True},
}

# Load trained forward models
model_gain = pickle.load(open(r"D:\UST Project\UST_Analog_automation\notebooks\new_data_exp\trained_models\model_gain_xgboost.pkl", "rb"))
model_pm   = pickle.load(open(r"D:\UST Project\UST_Analog_automation\notebooks\new_data_exp\trained_models\model_pm_xgboost.pkl", "rb"))
model_ugf  = pickle.load(open(r"D:\UST Project\UST_Analog_automation\notebooks\new_data_exp\trained_models\model_ugf_xgboost.pkl", "rb"))

In [3]:
GAIN_TARGET = 18.742711		   # example
PM_MAX      = 87.258927   # constraint
UGF_TARGET  = 12.859450		  # example

In [4]:
# ============================================================
# 4. INVERSE LOSS FUNCTION
# ============================================================
def inverse_loss(x):
    """
    x shape: (1, 4)
    """
    gain = model_gain.predict(x)[0]
    pm   = model_pm.predict(x)[0]
    ugf  = model_ugf.predict(x)[0]

    loss = (
        abs(gain - GAIN_TARGET) +
        max(0.0, PM_MAX - pm) +
        abs(ugf - UGF_TARGET)
    )
    return loss

In [5]:
def objective(trial):
    x = []

    for f in feature_names:
        low, high = bounds[f]

        if feature_config[f]["log"]:
            val = trial.suggest_float(f, low, high, log=True)
        else:
            val = trial.suggest_float(f, low, high)

        x.append(val)

    x = np.array(x).reshape(1, -1)
    return inverse_loss(x)

In [6]:
study = optuna.create_study(
    direction="minimize",
    sampler=optuna.samplers.TPESampler(
        seed=42,
        n_startup_trials=50
    )
)

study.optimize(objective, n_trials=200, show_progress_bar=True)

[I 2026-03-04 17:30:56,441] A new study created in memory with name: no-name-148a3076-7a01-44d8-b30d-82eb04ecde25

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-03-04 17:30:56,463] Trial 0 finished with value: 13.036462783813477 and parameters: {'a': 6.59269988761102e-06, 'b': 0.0003698270095505816, 'c': 4.462395092148129e-06, 'd': 6.37710619087497e-05}. Best is trial 0 with value: 13.036462783813477.
[I 2026-03-04 17:30:56,468] Trial 1 finished with value: 26.337921142578125 and parameters: {'a': 5.478384061253937e-06, 'b': 6.068172801571452e-05, 'c': 2.521068595986405e-06, 'd': 7.999520174016835e-05}. Best is trial 0 with value: 13.036462783813477.
[I 2026-03-04 17:30:56,473] Trial 2 finished with value: 32.57509231567383 and parameters: {'a': 7.987991737671789e-06, 'b': 0.0002754395954973417, 'c': 2.44222604110033e-06, 'd': 8.734449411161188e-05}. Best is trial 0 with value: 13.036462783813477.
[I 2026-03-04 17:30:56,477] Trial 3 finished with value: 1.9678878784179688 and parameters: {'a': 9.717639958417919e-06, 'b': 8.259972294864981e-05, 'c': 2.7997458439219924e-06, 'd': 4.485592596776692e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,480] Trial 4 finished with value: 2.6548070907592773 and parameters: {'a': 6.211483270845925e-06, 'b': 0.00020412977962415204, 'c': 3.4606444448191815e-06, 'd': 4.9146974437445996e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,484] Trial 5 finished with value: 6.234313011169434 and parameters: {'a': 8.06099958229809e-06, 'b': 5.4262986249169684e-05, 'c': 3.074069558843862e-06, 'd': 5.237739292708591e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,488] Trial 6 finished with value: 9.54122257232666 and parameters: {'a': 7.064223059395701e-06, 'b': 0.000305432742323517, 'c': 2.8424089252279494e-06, 'd': 5.9368702822201856e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,492] Trial 7 finished with value: 66.46104431152344 and parameters: {'a': 7.929321846882619e-06, 'b': 1.8069168742707666e-05, 'c': 4.015814497492794e-06, 'd': 4.436905135059032e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,495] Trial 8 finished with value: 24.325374603271484 and parameters: {'a': 5.071993793550197e-06, 'b': 0.0003691156199945631, 'c': 5.439279965906966e-06, 'd': 7.617328441539014e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,499] Trial 9 finished with value: 25.48013687133789 and parameters: {'a': 6.2134389123683105e-06, 'b': 3.799436444358072e-05, 'c': 4.2854172279401104e-06, 'd': 5.575670798948261e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,502] Trial 10 finished with value: 28.033851623535156 and parameters: {'a': 5.322902052338975e-06, 'b': 0.000192623372374065, 'c': 2.4709583163365733e-06, 'd': 8.297361707345819e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,506] Trial 11 finished with value: 8.93967342376709 and parameters: {'a': 5.976766141255695e-06, 'b': 0.00025772057234364304, 'c': 3.1254581023085998e-06, 'd': 5.966287580700375e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,509] Trial 12 finished with value: 17.807117462158203 and parameters: {'a': 7.62812723697779e-06, 'b': 7.190821683042004e-05, 'c': 5.457526788101741e-06, 'd': 7.405631685508992e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,512] Trial 13 finished with value: 10.131246566772461 and parameters: {'a': 1.064032853660455e-05, 'b': 0.00034808703397174, 'c': 3.9831306681489e-06, 'd': 8.386090441252278e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,515] Trial 14 finished with value: 4.413577079772949 and parameters: {'a': 5.173737901106338e-06, 'b': 7.62371570964713e-05, 'c': 2.4937552888076592e-06, 'd': 5.0587734856376605e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,518] Trial 15 finished with value: 15.300615310668945 and parameters: {'a': 6.672144709192133e-06, 'b': 0.00010555452914591692, 'c': 4.84359036019393e-06, 'd': 5.195270523379218e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,522] Trial 16 finished with value: 21.281421661376953 and parameters: {'a': 6.0900185450470645e-06, 'b': 0.0002111082879220838, 'c': 2.7043823008886147e-06, 'd': 7.57741529957081e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,525] Trial 17 finished with value: 19.720104217529297 and parameters: {'a': 5.112980584423259e-06, 'b': 0.00038389813013935825, 'c': 4.617207467475388e-06, 'd': 4.544163845825892e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,529] Trial 18 finished with value: 11.725367546081543 and parameters: {'a': 4.8225112371119566e-06, 'b': 0.00031721376175364486, 'c': 4.368359125306281e-06, 'd': 7.12178631067335e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,532] Trial 19 finished with value: 10.354646682739258 and parameters: {'a': 9.226793906595098e-06, 'b': 2.880330288437459e-05, 'c': 3.251758679614844e-06, 'd': 4.236120918689747e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,536] Trial 20 finished with value: 1.9754753112792969 and parameters: {'a': 9.973400548968826e-06, 'b': 0.00024246241036760587, 'c': 3.176684128279207e-06, 'd': 4.052464525295785e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,540] Trial 21 finished with value: 12.686009407043457 and parameters: {'a': 6.247057630154797e-06, 'b': 0.00012649601960341476, 'c': 4.453376137841825e-06, 'd': 6.590791502827409e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,543] Trial 22 finished with value: 15.005682945251465 and parameters: {'a': 1.0179230067714932e-05, 'b': 0.00018369118089456562, 'c': 2.6559454315475213e-06, 'd': 7.027304110798463e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,547] Trial 23 finished with value: 14.95185375213623 and parameters: {'a': 9.145184547767176e-06, 'b': 0.0002183363247050562, 'c': 4.612212050574276e-06, 'd': 5.834941960298048e-05}. Best is trial 3 with value: 1.9678878784179688.
[I 2026-03-04 17:30:56,551] Trial 24 finished with value: 1.5991477966308594 and parameters: {'a': 7.474717499124772e-06, 'b': 0.00016631307135455927, 'c': 2.4522508303192285e-06, 'd': 4.2075837080453e-05}. Best is trial 24 with value: 1.5991477966308594.
[I 2026-03-04 17:30:56,554] Trial 25 finished with value: 8.012803077697754 and parameters: {'a': 4.929540602817032e-06, 'b': 0.0002475630772122404, 'c': 3.1324701779015245e-06, 'd': 5.908448200302371e-05}. Best is trial 24 with value: 1.5991477966308594.
[I 2026-03-04 17:30:56,557] Trial 26 finished with value: 17.575397491455078 and parameters: {'a': 1.0356300199328617e-05, 'b': 9.697445277590612e-05, 'c': 3.397994178319288e-06, 'd': 7.283774693594149e-05}. Best is trial 24 with value: 1.5991477966308594.
[I 2026-03-04 17:30:56,559] Trial 27 finished with value: 7.049283981323242 and parameters: {'a': 5.82684748513348e-06, 'b': 2.9945115641481626e-05, 'c': 3.067842431403213e-06, 'd': 4.4020697072544166e-05}. Best is trial 24 with value: 1.5991477966308594.
[I 2026-03-04 17:30:56,563] Trial 28 finished with value: 147.7538604736328 and parameters: {'a': 1.0552330642980089e-05, 'b': 0.00031435810034221657, 'c': 4.104772762118505e-06, 'd': 8.035418320123899e-05}. Best is trial 24 with value: 1.5991477966308594.
[I 2026-03-04 17:30:56,567] Trial 29 finished with value: 142.30929565429688 and parameters: {'a': 9.483614776471383e-06, 'b': 7.257558499361494e-05, 'c': 5.112722632110138e-06, 'd': 6.064523017394982e-05}. Best is trial 24 with value: 1.5991477966308594.
[I 2026-03-04 17:30:56,574] Trial 30 finished with value: 1.9754753112792969 and parameters: {'a': 9.513941353648752e-06, 'b': 0.00034857870918806894, 'c': 3.142166095096753e-06, 'd': 4.215293101604646e-05}. Best is trial 24 with value: 1.5991477966308594.
[I 2026-03-04 17:30:56,581] Trial 31 finished with value: 9.304998397827148 and parameters: {'a': 5.822588331874454e-06, 'b': 0.00016614454537860395, 'c': 4.799783910646512e-06, 'd': 7.962695300736946e-05}. Best is trial 24 with value: 1.5991477966308594.
[I 2026-03-04 17:30:56,587] Trial 32 finished with value: 0.6083126068115234 and parameters: {'a': 4.828357961202828e-06, 'b': 0.00019868024103010073, 'c': 3.418289183682043e-06, 'd': 4.635128113953638e-05}. Best is trial 32 with value: 0.6083126068115234.
[I 2026-03-04 17:30:56,593] Trial 33 finished with value: 4.34549617767334 and parameters: {'a': 5.313111253904574e-06, 'b': 0.00013133199782235701, 'c': 5.335561416988935e-06, 'd': 5.04966305546759e-05}. Best is trial 32 with value: 0.6083126068115234.
[I 2026-03-04 17:30:56,598] Trial 34 finished with value: 34.605613708496094 and parameters: {'a': 7.449791919298789e-06, 'b': 0.00027347374229316117, 'c': 3.2660173976202607e-06, 'd': 8.748316186753038e-05}. Best is trial 32 with value: 0.6083126068115234.
[I 2026-03-04 17:30:56,600] Trial 35 finished with value: 18.03887176513672 and parameters: {'a': 1.084924455889034e-05, 'b': 9.794308647200041e-05, 'c': 3.6575236954286463e-06, 'd': 4.9550433413879986e-05}. Best is trial 32 with value: 0.6083126068115234.
[I 2026-03-04 17:30:56,605] Trial 36 finished with value: 103.43869018554688 and parameters: {'a': 6.1102070479945024e-06, 'b': 1.4348989322660638e-05, 'c': 4.022691851352983e-06, 'd': 5.8790267378872045e-05}. Best is trial 32 with value: 0.6083126068115234.
[I 2026-03-04 17:30:56,609] Trial 37 finished with value: 100.69612121582031 and parameters: {'a': 5.01399876639201e-06, 'b': 0.00010839322380622403, 'c': 5.181219634309469e-06, 'd': 4.704185498350994e-05}. Best is trial 32 with value: 0.6083126068115234.
[I 2026-03-04 17:30:56,613] Trial 38 finished with value: 5.320418357849121 and parameters: {'a': 5.426992065387442e-06, 'b': 0.00019039668324048774, 'c': 5.5323255368483686e-06, 'd': 4.714134236515814e-05}. Best is trial 32 with value: 0.6083126068115234.
[I 2026-03-04 17:30:56,616] Trial 39 finished with value: 18.218158721923828 and parameters: {'a': 8.483430678382443e-06, 'b': 0.00029626934490521733, 'c': 2.935325998710263e-06, 'd': 7.117015887726076e-05}. Best is trial 32 with value: 0.6083126068115234.
[I 2026-03-04 17:30:56,620] Trial 40 finished with value: 126.79920959472656 and parameters: {'a': 6.555063335618652e-06, 'b': 0.0002459663990256549, 'c': 4.105210849991878e-06, 'd': 6.046218952046348e-05}. Best is trial 32 with value: 0.6083126068115234.
[I 2026-03-04 17:30:56,622] Trial 41 finished with value: 0.5456600189208984 and parameters: {'a': 5.181622581509813e-06, 'b': 0.00032493191901196753, 'c': 3.149567053504136e-06, 'd': 4.497443397256532e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,625] Trial 42 finished with value: 56.86668014526367 and parameters: {'a': 4.968731658835679e-06, 'b': 0.00022985682309657719, 'c': 4.261271421133921e-06, 'd': 3.894351611397697e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,629] Trial 43 finished with value: 74.70491790771484 and parameters: {'a': 7.4076353367382115e-06, 'b': 8.810665270580019e-05, 'c': 4.145909818160137e-06, 'd': 4.4513733601312224e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,632] Trial 44 finished with value: 83.79469299316406 and parameters: {'a': 8.619662967978646e-06, 'b': 0.00015043970164909737, 'c': 5.30769711346668e-06, 'd': 4.3145523152119574e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,634] Trial 45 finished with value: 134.74880981445312 and parameters: {'a': 6.408342822064695e-06, 'b': 4.414109763642003e-05, 'c': 5.2538422267017525e-06, 'd': 8.075543097898879e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,639] Trial 46 finished with value: 13.946784973144531 and parameters: {'a': 5.972522139882698e-06, 'b': 0.0002567331999216542, 'c': 4.796561749432632e-06, 'd': 6.146561540466501e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,643] Trial 47 finished with value: 31.657743453979492 and parameters: {'a': 7.518658414415043e-06, 'b': 9.408032349321389e-05, 'c': 2.596993716907229e-06, 'd': 8.212696895474595e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,646] Trial 48 finished with value: 2.620941162109375 and parameters: {'a': 1.0293763343369835e-05, 'b': 0.0002462758970879897, 'c': 3.1986471472072175e-06, 'd': 5.1621692683647074e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,649] Trial 49 finished with value: 167.10365295410156 and parameters: {'a': 8.879245714686918e-06, 'b': 0.00034897508372231853, 'c': 5.089070325405271e-06, 'd': 7.435451080716379e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,657] Trial 50 finished with value: 1.2693872451782227 and parameters: {'a': 5.595740060323551e-06, 'b': 0.00015288047559377092, 'c': 2.882105497630222e-06, 'd': 4.028371372559442e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,668] Trial 51 finished with value: 1.2693872451782227 and parameters: {'a': 5.638859248289237e-06, 'b': 0.00016771420894795777, 'c': 2.8316305493625855e-06, 'd': 4.0065515527695094e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,675] Trial 52 finished with value: 1.2693872451782227 and parameters: {'a': 5.66983997613411e-06, 'b': 0.0001711093166749878, 'c': 2.8913346628431454e-06, 'd': 3.877961157101638e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,682] Trial 53 finished with value: 1.2693872451782227 and parameters: {'a': 5.691989982062809e-06, 'b': 0.0001703213927588446, 'c': 2.8854746845299498e-06, 'd': 3.865279619656917e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,691] Trial 54 finished with value: 1.2693872451782227 and parameters: {'a': 5.615316485160486e-06, 'b': 0.00014722989359088585, 'c': 2.890742145908545e-06, 'd': 3.847943391207694e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,698] Trial 55 finished with value: 1.9754753112792969 and parameters: {'a': 5.608139748258116e-06, 'b': 0.00017386451110460935, 'c': 2.988070954930342e-06, 'd': 4.004680351307722e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,709] Trial 56 finished with value: 1.2693872451782227 and parameters: {'a': 6.978188997580528e-06, 'b': 0.00020719095288043753, 'c': 2.748382808730583e-06, 'd': 4.0206486143973216e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,717] Trial 57 finished with value: 1.4370670318603516 and parameters: {'a': 5.283372126040702e-06, 'b': 0.00014709625311237507, 'c': 2.8081196599823313e-06, 'd': 4.1037070653501015e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,724] Trial 58 finished with value: 4.586953163146973 and parameters: {'a': 5.619343148212102e-06, 'b': 0.0001802024994586742, 'c': 3.3895413546861473e-06, 'd': 5.4199642161255304e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,734] Trial 59 finished with value: 19.38518524169922 and parameters: {'a': 4.834343523086012e-06, 'b': 0.00012553045958377986, 'c': 3.6300400895152713e-06, 'd': 4.656525813179276e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,740] Trial 60 finished with value: 2.0286741256713867 and parameters: {'a': 5.182328599973513e-06, 'b': 0.00016159083973826366, 'c': 3.0245593074124336e-06, 'd': 3.952662586913861e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,749] Trial 61 finished with value: 1.2693872451782227 and parameters: {'a': 5.610620719570126e-06, 'b': 0.00014255684822698605, 'c': 2.9138989807509407e-06, 'd': 3.845169016937716e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,756] Trial 62 finished with value: 1.2693872451782227 and parameters: {'a': 5.482890467003516e-06, 'b': 0.00019447374714440558, 'c': 2.879961192338185e-06, 'd': 4.096934319317231e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,764] Trial 63 finished with value: 2.2636966705322266 and parameters: {'a': 5.887240398274322e-06, 'b': 0.00022464679033051206, 'c': 2.573651523680316e-06, 'd': 4.3211479394038115e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,772] Trial 64 finished with value: 1.2477140426635742 and parameters: {'a': 5.47423903833496e-06, 'b': 0.00011792698033079458, 'c': 2.7111444498987654e-06, 'd': 4.1465560557840106e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,782] Trial 65 finished with value: 1.4370670318603516 and parameters: {'a': 5.183976466324395e-06, 'b': 0.00013286267953482108, 'c': 2.723206860130989e-06, 'd': 4.1719895969732175e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,789] Trial 66 finished with value: 18.14223861694336 and parameters: {'a': 5.448007029075141e-06, 'b': 0.00011702887864857117, 'c': 3.5123322615170864e-06, 'd': 4.555618486735648e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,796] Trial 67 finished with value: 1.6830101013183594 and parameters: {'a': 5.727690787842209e-06, 'b': 0.0001629211430327539, 'c': 2.788905078904979e-06, 'd': 4.330361800808615e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,804] Trial 68 finished with value: 19.56924057006836 and parameters: {'a': 5.058779695144631e-06, 'b': 0.00020382962840570585, 'c': 3.826555498072912e-06, 'd': 3.9594130400261424e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,813] Trial 69 finished with value: 2.1276025772094727 and parameters: {'a': 5.319359022355341e-06, 'b': 6.134453200349658e-05, 'c': 2.9812877046154927e-06, 'd': 4.1448916516847015e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,821] Trial 70 finished with value: 4.232770919799805 and parameters: {'a': 6.3443985294299385e-06, 'b': 0.0001135381235335081, 'c': 2.640431975068197e-06, 'd': 4.792523963613078e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,828] Trial 71 finished with value: 1.2693872451782227 and parameters: {'a': 5.7233404847091155e-06, 'b': 0.00015177170880768115, 'c': 2.8613004485594356e-06, 'd': 3.858640924569794e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,838] Trial 72 finished with value: 2.5355491638183594 and parameters: {'a': 5.502920143526153e-06, 'b': 0.0001762285244001787, 'c': 3.2519365053366083e-06, 'd': 3.981605354945342e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,847] Trial 73 finished with value: 0.9493627548217773 and parameters: {'a': 6.040675420450692e-06, 'b': 0.00015018101238932288, 'c': 3.0444347025055375e-06, 'd': 4.283370652147577e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,855] Trial 74 finished with value: 0.9493627548217773 and parameters: {'a': 6.044190575810574e-06, 'b': 0.00013594845528552333, 'c': 3.077408038545718e-06, 'd': 4.571895185778955e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,865] Trial 75 finished with value: 0.7556133270263672 and parameters: {'a': 6.0920709115080475e-06, 'b': 0.00013726227398865268, 'c': 3.3459397840333146e-06, 'd': 4.605490517455698e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,877] Trial 76 finished with value: 0.7556133270263672 and parameters: {'a': 6.914581179408864e-06, 'b': 0.00013902885213609595, 'c': 3.3145233153985283e-06, 'd': 4.589280806818201e-05}. Best is trial 41 with value: 0.5456600189208984.
[I 2026-03-04 17:30:56,884] Trial 77 finished with value: 2.6548070907592773 and parameters: {'a': 7.040747018740236e-06, 'b': 0.00013446095134397255, 'c': 3.349606358183441e-06, 'd': 4.830033111464602e-05}. Best is trial 41 with value: 0.5456600189208984.

In [7]:
best_params = study.best_params
x_best = np.array([best_params[f] for f in feature_names]).reshape(1, -1)

gain_best = model_gain.predict(x_best)[0]
pm_best   = model_pm.predict(x_best)[0]
ugf_best  = model_ugf.predict(x_best)[0]

print("\n===== INVERSE PREDICTION =====")
for k in feature_names:
    print(f"{k} = {best_params[k]:.6e}")

print("\nPredicted outputs:")
print(f"GAIN = {gain_best:.6f}")
print(f"PM   = {pm_best:.6f}")
print(f"UGF  = {ugf_best:.6f}")
print(f"Final loss = {study.best_value:.6f}")

===== INVERSE PREDICTION =====
a = 6.827679e-06
b = 8.316329e-05
c = 3.215640e-06
d = 4.593693e-05

Predicted outputs:
GAIN = 18.822449
PM   = 93.338928
UGF  = 13.144586
Final loss = 0.364874

In [8]:
import pandas as pd

df = pd.read_csv("Opam.csv")
pd.set_option('display.float_format', '{:.10f}'.format)


df.head()

,a,b,c,d,gain,pm,ugf
0,0.0000112000,0.0001320120,0.0000024000,0.0000384000,18.7427113100,87.2589267500,12.8594501900
1,0.0000112000,0.0001320120,0.0000024000,0.0000427000,20.0224857400,88.4842564900,14.2978920500
2,0.0000112000,0.0001320120,0.0000024000,0.0000469000,21.2202001200,89.6240725500,15.5129365100
3,0.0000112000,0.0001320120,0.0000024000,0.0000512000,22.3550526600,90.9081618400,17.4676334600
4,0.0000112000,0.0001320120,0.0000024000,0.0000555000,23.4437963200,92.1196945900,19.5720128900

In [9]:
print("\n===== STABILITY CHECK =====")
for i in range(5):
    noise = np.random.normal(0, 5e-8, size=x_best.shape)
    g = model_gain.predict(x_best + noise)[0]
    p = model_pm.predict(x_best + noise)[0]
    u = model_ugf.predict(x_best + noise)[0]
    print(f"{i+1}: GAIN={g:.4f}, PM={p:.4f}, UGF={u:.4f}")

===== STABILITY CHECK =====
1: GAIN=18.8224, PM=93.3389, UGF=13.1446
2: GAIN=18.8224, PM=93.3389, UGF=13.1446
3: GAIN=18.8224, PM=93.3389, UGF=13.1446
4: GAIN=18.8224, PM=93.3389, UGF=13.1446
5: GAIN=18.8224, PM=93.3389, UGF=13.1446

In [10]:
print("\n===== TOP 5 INVERSE SOLUTIONS =====")
top_trials = sorted(study.trials, key=lambda t: t.value)[:5]

for i, t in enumerate(top_trials):
    print(f"\nSolution {i+1} | Loss = {t.value:.6f}")
    for f in feature_names:
        print(f"{f} = {t.params[f]:.6e}")

===== TOP 5 INVERSE SOLUTIONS =====

Solution 1 | Loss = 0.364874
a = 6.827679e-06
b = 8.316329e-05
c = 3.215640e-06
d = 4.593693e-05

Solution 2 | Loss = 0.364874
a = 6.585031e-06
b = 5.687620e-05
c = 3.439008e-06
d = 4.410141e-05

Solution 3 | Loss = 0.364874
a = 6.540730e-06
b = 4.621925e-05
c = 3.436176e-06
d = 4.484351e-05

Solution 4 | Loss = 0.364874
a = 6.751392e-06
b = 4.482670e-05
c = 3.315431e-06
d = 4.616248e-05

Solution 5 | Loss = 0.364874
a = 6.444005e-06
b = 7.278521e-05
c = 3.217114e-06
d = 4.461746e-05

In [11]:
import pandas as pd 

df = pd.read_csv("Opam.csv")

df.head()

,a,b,c,d,gain,pm,ugf
0,0.0000112000,0.0001320120,0.0000024000,0.0000384000,18.7427113100,87.2589267500,12.8594501900
1,0.0000112000,0.0001320120,0.0000024000,0.0000427000,20.0224857400,88.4842564900,14.2978920500
2,0.0000112000,0.0001320120,0.0000024000,0.0000469000,21.2202001200,89.6240725500,15.5129365100
3,0.0000112000,0.0001320120,0.0000024000,0.0000512000,22.3550526600,90.9081618400,17.4676334600
4,0.0000112000,0.0001320120,0.0000024000,0.0000555000,23.4437963200,92.1196945900,19.5720128900